### ISSUE TITLE
Portfolio.side works with buy&sell, Position.side with LONG & SHORT

### ISSUE THREAD

**Issue by Wesseldr** [mhallsmoore/qsforex#2]
The portfolio class works with the variable 'side' with possible values: 'buy' and 'sell' where the position class except it to be LONG or SHORT (line 21 position.py)

**Comment by mhallsmoore** [comment]
Hi Wessel,

I've actually modified this now by completely replacing how the Portfolio and Position handling is carried out. The Position class does a lot more of the "heavy lifting", which stops overridden Portfolio classes from having to do too much "boilerplate".

There is still more to do, however, but it certainly fixes this particular issue!

Mike.

**Comment by Wesseldr** [comment]
thank you!
