### ISSUE TITLE
tick interval from oanda is not constant

### ISSUE THREAD

**Issue by woodjude** [mhallsmoore/qsforex#27]
Hi Mike, Thanks for sharing the code. I noticed the time interval between two ticks from Oanda is not constant. Sometimes it is short, around 0.1s. Sometimes, it can be more than 5 seconds. I am wondering is it my internet problem or code itself?
Jack

**Comment by crzluckbox** [comment]
It is normal for ticks to come at irregular intervals. They do not represent measurements of time, but instead come through as trades occur that affect the price of the product.

**Comment by mhallsmoore** [comment]
Hi woodjude,

Crzluckbox is correct, the ticks don't come in at regular intervals as they represent a change in a particular asset price, not a measurement of time. The ticks that I use for this contain both bid and ask prices. Hence we are not using order book data, which is much more detailed.

I do plan on eventually being able to "bin" the ticks into Open-High-Low-Close bars at various periods, but for now QSForex uses solely tick data in an event-driven fashion.

Hope that helps!

**Comment by woodjude** [comment]
I see. Thank you mhallsmoore and crzluckbox.
