### ISSUE TITLE
How hard to apply this backtester to another type of instrument?

### ISSUE THREAD

**Issue by richwu** [mhallsmoore/qsforex#37]
HI, I'm looking at the code trying to figure out how hard to make it works to another instrument, like commodity. I'm getting into commodity trading strategy, focusing on intraday pair trading arb.

thanks

**Comment by mhallsmoore** [comment]
Hi Richard,

I'm actually working on a new backtester called QSTrader (https://github.com/mhallsmoore/qstrader), also free and fully open-source under the same license type (MIT) as QSForex. They're very similar in design, with the exception that I'll (eventually) be incorporating the forex instrument handling from QSForex into QSTrader. I've designed it for the time being to be compatible with InteractiveBrokers, but will also be adding OANDA eventually.

At this stage it only supports equities (although you can gain commodities exposure via ETFs), so it will be a bit longer before it supports full futures trading.

If you want to read a bit more about the project, I've written a few posts about it:
- https://www.quantstart.com/articles/Announcing-the-QuantStart-Advanced-Trading-Infrastructure-Article-Series
- https://www.quantstart.com/articles/Advanced-Trading-Infrastructure-Position-Class
- https://www.quantstart.com/articles/Advanced-Trading-Infrastructure-Portfolio-Class
- https://www.quantstart.com/articles/Advanced-Trading-Infrastructure-Portfolio-Handler-Class

I'll be continuing to write articles about its development on the site. At the moment, it's not as well documented as QSForex, but I am in the process of writing the docs, so as soon as they're up, I'll make a post to the site.

I hope that helps!

Mike.

**Comment by richwu** [comment]
Thanks for your very quick and specified reply. I've been following all your posts quite a while.  I'm appreciated to your efforts and suggestions.
