### ISSUE TITLE
Execution module

### ISSUE THREAD

**Issue by xenu256** [mhallsmoore/qsforex#6]
First run of trading/trading.py:

"Import error: No module named qsforex.execution.execution"

**Comment by mhallsmoore** [comment]
Hi Xenu,

Did you create a virtual environment and a symlink pointing to your directory installation of QSForex?

e.g. on Ubuntu/Linux, for Python 2.7.x, it would require something like this:

ln -s /path/to/your/qsforex/ /path/to/your/qsforex/virtualenv/lib/python2.7/site-packages/qsforex

Mike.

**Comment by xenu256** [comment]
Yup.

![untitled](https://cloud.githubusercontent.com/assets/7689499/7570063/c45106c2-f815-11e4-9056-3179fb99599a.png)

**Comment by mhallsmoore** [comment]
Hi Xenu,

I think the issue is that when you used mklink /D ..., it should have been mklink /J ..., which creates a "junction" instead of a "soft" symlink. If you first delete the qsforex symlink from the anaconda site-packages directory and then run:

mklink \J link_dir target_dir

With link_dir and target_dir as you originally specified, it might fix the problem.

Let me know how you get on.

Mike.

**Comment by xenu256** [comment]
Same thing, tried various variants, will try later with fresh Windows install on another PC. Will post results.

**Comment by xenu256** [comment]
OK, tried it, doesn't work, probably of Anaconda/Windows installation (numpy & ipython are older versions and can't be updated). That's too much work on Win, I'll better will make Unix partition.

**Comment by mhallsmoore** [comment]
Hi Xenu,

You could also try a Virtualbox with Ubuntu which would stop you having to make a hard Unix partition. At least that way you can "try it out" before you commit to a dual-boot system.

I'm going to try and package up QSForex with the Python package manager to make this process somewhat easier, so I'll put that as a separate issue for the future.

Mike.

**Comment by petemere** [comment]
In case it is of use to others, I'm using Windows 7 sp1 and the Anaconda distro, and the following command worked for me:
`MKLINK /D C:\Users\tplj\Anaconda\envs\qsfx\Lib\site-packages\qsforex "C:\Users\tplj\Desktop\Pete\Trading Research\QSFX\qsforex"`
