### ISSUE TITLE
Is project alive?

### ISSUE THREAD

**Issue by estatic** [mhallsmoore/qsforex#60]
Hi there!

is this project still alive? I see many pull requests still opened.

**Comment by rymoore** [comment]
I'm interested too!

**Comment by yabolgha** [comment]
It seems that the project is discontinued! sad!

**Comment by mhallsmoore** [comment]
Hi all,

Thanks for the interest in QSForex. As it happens, QSForex is eventually going to be "merged" into the larger QSTrader project, which lives [here](https://github.com/mhallsmoore/qstrader).

QSForex was purely designed to connect to the OANDA API specifically and trade only forex pairs, but QSTrader is designed to handle predominantly equities, but will support forex positions in the future. In particular it will eventually be designed to work with many brokerages, including Interactive Brokers, OANDA etc.

Cheers,

-Mike.

**Comment by estatic** [comment]
Hi Mike,

thanks for fast reply. So, as I undertood by your reply, exaclty this project will be "closed" as you are working on new one which is going to contain this one. right?

So, seems no reason to keep an eye on this project and better to look at new one.

Cheers,
Ivan
